#!/bin/bash

cd generated

DRIVER=$1
METHOD=$2
MUTATION=$3
BRANCH=$5
TRIALS=$7

javac -cp \
        ../../fuzz/src/main/java/edu/ucla/cs/jqf/bigfuzz:/home/ahmad/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:$(../../scripts/classpath.sh) \
        ../../fuzz/src/main/java/edu/ucla/cs/jqf/bigfuzz/{{ProvFuzzMutation,ProvFuzzGuidance,ProvFuzzDriver}.java,$MUTATION.java} \
         -d ../../fuzz/target/classes \
         && \
../../bin/jqf-provfuzz \
        -c ../../customarray/target/classes:$(../../scripts/classpath.sh)  \
        $DRIVER $METHOD $BRANCH $TRIALS


